SistemaDeVentas/Models/ErrorViewModel.cs
namespace SistemaDeVentas.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SistemaDeVentas/Controllers/AgregaUsuarios/ValidaUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ML_Sistema_Ventas;
using BL_Sistema_Ventas;
using System.Data;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SistemaDeVentas.Controllers.AgregaUsuarios
{
    public class ValidaUsuariosController : Controller
    {
        BL_ValidaUsuarios blUsuarios;

        public ValidaUsuariosController(IConfiguration configuracion)
        {
            blUsuarios = new(configuracion);
        }

        [HttpPost]
        public ActionResult ValidaUsuariosRegistrado([FromBody] DatosRegistroModel datosUsuario)
        {
            string mensajeError = string.Empty;
            DataTable tablaUsuario = new();
            try
            {
                tablaUsuario = blUsuarios.ObtieneUsuarioRegistrado(datosUsuario);
                if (tablaUsuario.Rows.Count > 0)
                {
                    return View("DatoEncontrado");
                }
                else
                {
                    return Json("NoDatos");
                }
            }
            catch (Exception ex)
            {
                mensajeError = ex.Message;
            }
            return View();
        }
        public ActionResult NuevoUsuario()
        {
            DatosRegistroModel model = new();
            return View("~/Views/AgregaUsuarios/NuevoUsuario.cshtml");
        }
    }
}

SistemaDeVentas/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SistemaDeVentas.Models;

namespace SistemaDeVentas.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SistemaDeVentas/Views/AgregaUsuarios/NuevoUsuario.cshtml
@model ML_Sistema_Ventas.DatosRegistroModel
<body>
    @using (Html.BeginForm("", "", FormMethod.Post, new { @id = "frmNuevoUs" }))
    {
        <div class="container">
            <div class="row">
                <div class="col-4 col-md-4">
                    @Html.Label("Nombre Completo")
                    @Html.TextBox("txtNombre", null, new { @class = "form-control borde", @id = "idNombre", @placeholder = "Nombre" })
                </div>
                <div class="col-4 col-md-4">
                    @Html.Label("Apellido")
                    @Html.TextBox("txtApellido", null, new { @class = "form-control borde", @id = "idApellido", @placeholder = "Apellido" })
                </div>
                <div class="col-4 col-md-4">
                    @Html.Label("Edad")
                    @Html.TextBox("txtEdad", null, new { @class = "form-control", @id = "idEdad", @placeholder = "Edad" })
                </div>
            </div>
            <div class="row pt-3">
                <div class="col-4 col-md-4">
                    <label>Correo:</label>
                    @Html.TextBoxFor(model => model.Correo, new { @class = "form-control borde", @id = "idCorreo", @placeholder = "IngreseCorreo@gmail.com" })
                </div>
                <div class="col-4 col-md-4">
                    <label>Contraseña:</label>
                    @Html.TextBox("txtContrasenia", null, new { @class = "form-control borde", @id = "idContrasenia", @onchange = "HabilitaCont()" })
                </div>
                <div class="col-4 col-md-4">
                    <label>Confirma contraseña:</label>
                    @Html.TextBox("txtConfCont", null, new { @class = "form-control borde", @id = "idConfCont", @disabled = "disabled" })
                </div>
            </div>
            <div class="row pt-3">
                <div class="col-4 col-md-4">
                    <span>M</span><input type="radio" id="idRadioM" />&nbsp;&nbsp;&nbsp;
                    <span>F</span><input type="radio" id="idRadioF" />&nbsp;&nbsp;&nbsp;
                    <span>Otro</span><input type="radio" id="idOtro" />
                </div>
            </div>
            <div class="col-12 col-md-12 AlineadoBtn pt-3">
                <a href="@Url.Action("Index","Home")" class="btn btn-danger" id="idBtnRegresa" type="button">Regresar</a>
                <button type="submit" class="btn btn-success" id="idBtnGuarda">Guardar</button>
            </div>
        </div>
    }


</body>
<style>
    .borde {
        border-radius: 20px;
    }
    .AlineadoBtn{
        text-align:right
    }
</style>
@section Scripts{
  <script>
      function HabilitaCont() {
          let ContraseniaConf = $('#idContrasenia').val();
          if (ContraseniaConf != '') {
              $('#idConfCont').prop('disabled',false);
          }
          else {
              $('#idConfCont').prop('disabled', true);
              $('#idConfCont').val("");
          }

      }
  </script>
}

SistemaDeVentas/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<div class="container" id="containerLogin">
    <div class="col-12 col-md-12" style="text-align:-webkit-center">
        <div class="col-12 col-md-6">
            <img src="~/Images/Login.png" alt="Logo de la aplicacion" style="border-radius:10%">
        </div>
        <div class="col-12 col-md-3 pt-3">
            <p>Usuario</p>
            <input type="text" class="form-control" id="idUsuario" />
        </div>
        <div class="col-12 col-md-3 pt-3">
            <p>Contaseña</p>
            <input type="text" class="form-control" id="idContrasenia" />
        </div>
        <div class="row">
            <div class="col-12 col-md-12 pt-3" style="text-align:-webkit-center">
                <button id="idIniciaSesion" class="btn btn-primary">Iniciar sesión</button>
                <a href="@Url.Action("NuevoUsuario", "ValidaUsuarios")" class="btn btn-primary">Registrarse</a>
             
            </div>
        </div>
    </div>

</div>

<script>
    var emailRegex = /^[a-zA-Z0-9._%+-]+@@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
    $(document).ready(function () {
       
        $('#idIniciaSesion').click(function () {

            var DatosUsuarioModel = {
                Correo : $('#idUsuario').val(),
                Contrasenia : $('#idContrasenia').val()
            }
            if (ValidaDatos($("#idUsuario").val(), $("#idContrasenia").val()) === true) {
                $.ajax({
                    url: '@Url.Action("ValidaUsuariosRegistrado", "ValidaUsuarios")',
                    type: "POST",
                    data: JSON.stringify(DatosUsuarioModel),
                    contentType: 'application/json; charset=utf-8',
                    dataType: "json",
                    success: function (response) {
                        if (response === "NoDatos") {
                            alert("Registro no encontrado, favor de validar contraseña y correo electronico ");
                        }
                        else {
                            alert("Correo electronico registrado");
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log("Error en la solicitud AJAX:", textStatus, errorThrown);
                    }
                });
            }
        });
    });
    function ValidaDatos(idUsuario, idContraseña) {
        if (idUsuario === "") {
            alert("Favor de ingresar el correo");
            return false;
        }
        if (idContraseña === "") {
            alert("Favor de ingresar la contraseña");
            return false;
        }
        if (!emailRegex.test(idUsuario)) {
            alert("El correo electronico no es valido");
            return false;
        }
        return true;
    }
</script>

SistemaDeVentas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaDeVentas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDeVentas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    #containerLogin {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh; /* Establece el contenedor al 100% de la altura de la ventana */
    }
</style>